stages:
  data_ingestion:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage01_data_ingestion.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage03_base_model.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage03_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage05_trainer.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage05_trainer.py
      - src/ChickenDiseaseClassification/components/callback.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage06_evaluation.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage06_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false