artifacts_root : artifacts




# ------------------------------------------ Data_Ingestion ------------------------------------ 


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SubramanyaNayak-github/Datasets/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/chicken_data.zip
  unzip_dir: artifacts/data_ingestion


# ------------------------------------------ Data_Validation ------------------------------------ 


data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["Coccidiosis", "Healthy"]



# ------------------------------------------ Base_Model ------------------------------------ 



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5